"""empty message

Revision ID: 64f3d96d9227
Revises: fde757ad0548
Create Date: 2023-05-04 13:43:53.912232

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '64f3d96d9227'
down_revision = 'fde757ad0548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_partners', 'id')
    op.alter_column('orders', 'is_deleted',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('partners', 'email',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partners', 'email',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('orders', 'is_deleted',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.add_column('order_partners',
                  sa.Column('id', sa.INTEGER(), autoincrement=False,
                            nullable=False))
    # ### end Alembic commands ###
